# Generated by Django 5.2.8 on 2025-11-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('kata_sandi', models.CharField(max_length=45)),
                ('peran', models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru'), ('siswa', 'Siswa')], default='siswa', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Pengguna',
                'db_table': 'pengguna',
            },
        ),
        migrations.CreateModel(
            name='StageGame',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('nama_stage', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Stage Game',
                'db_table': 'stage_game',
            },
        ),
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kuis', models.CharField(max_length=45)),
                ('durasi', models.IntegerField()),
                ('id_pengguna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kuis_dibuat', to='main.pengguna')),
            ],
            options={
                'verbose_name_plural': 'Kuis',
                'db_table': 'kuis',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=45)),
                ('token', models.CharField(max_length=45, unique=True)),
                ('id_guru', models.ForeignKey(limit_choices_to={'peran': 'guru'}, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_diajar', to='main.pengguna')),
            ],
            options={
                'verbose_name_plural': 'Kelas',
                'db_table': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id_hasil_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('skor_kuis', models.IntegerField()),
                ('waktu_kuis', models.TimeField()),
                ('percobaan_kuis', models.IntegerField()),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_kuis', to='main.kuis')),
                ('id_siswa', models.ForeignKey(limit_choices_to={'peran': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_kuis', to='main.pengguna')),
            ],
            options={
                'verbose_name_plural': 'Hasil Kuis',
                'db_table': 'hasil_kuis',
            },
        ),
        migrations.CreateModel(
            name='HasilEvaluasi',
            fields=[
                ('id_hasil_evaluasi', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_evaluasi', to='main.kuis')),
                ('id_siswa', models.ForeignKey(limit_choices_to={'peran': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_evaluasi', to='main.pengguna')),
            ],
            options={
                'verbose_name_plural': 'Hasil Evaluasi',
                'db_table': 'hasil_evaluasi',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('nama_section', models.CharField(max_length=45)),
                ('urutan', models.IntegerField()),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.kuis')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'db_table': 'section',
                'ordering': ['urutan'],
                'unique_together': {('id_kuis', 'urutan')},
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nama_item', models.CharField(max_length=45)),
                ('jenis_item', models.CharField(choices=[('pilihan_ganda', 'Pilihan Ganda'), ('esai', 'Esai')], default='pilihan_ganda', max_length=20)),
                ('urutan', models.IntegerField()),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.section')),
            ],
            options={
                'verbose_name_plural': 'Section Items',
                'db_table': 'section_item',
                'ordering': ['urutan'],
                'unique_together': {('id_section', 'urutan')},
            },
        ),
        migrations.CreateModel(
            name='HasilGame',
            fields=[
                ('id_hasil_game', models.AutoField(primary_key=True, serialize=False)),
                ('skor_game', models.IntegerField()),
                ('waktu_game', models.TimeField()),
                ('percobaan_game', models.IntegerField()),
                ('id_siswa', models.ForeignKey(limit_choices_to={'peran': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_game', to='main.pengguna')),
                ('id_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_game', to='main.stagegame')),
            ],
            options={
                'verbose_name_plural': 'Hasil Game',
                'db_table': 'hasil_game',
            },
        ),
        migrations.CreateModel(
            name='AnggotaKelas',
            fields=[
                ('id_anggota', models.AutoField(primary_key=True, serialize=False)),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='main.kelas')),
                ('id_siswa', models.ForeignKey(limit_choices_to={'peran': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='keanggotaan_kelas', to='main.pengguna')),
            ],
            options={
                'verbose_name_plural': 'Anggota Kelas',
                'db_table': 'anggota_kelas',
                'unique_together': {('id_kelas', 'id_siswa')},
            },
        ),
        migrations.CreateModel(
            name='ProgresItem',
            fields=[
                ('id_progres', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('belum_selesai', 'Belum Selesai'), ('selesai', 'Selesai')], default='belum_selesai', max_length=15)),
                ('id_pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_item', to='main.pengguna')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_item', to='main.sectionitem')),
            ],
            options={
                'verbose_name_plural': 'Progres Item',
                'db_table': 'progres_item',
                'unique_together': {('id_pengguna', 'id_item')},
            },
        ),
    ]
