# Generated by Django 5.2.8 on 2025-12-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kuis', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('kata_sandi', models.CharField(max_length=255)),
                ('peran', models.CharField(choices=[('siswa', 'Siswa'), ('guru', 'Guru')], max_length=10)),
            ],
            options={
                'db_table': 'pengguna',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('nama_section', models.CharField(max_length=45)),
                ('urutan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StageGame',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('nama_stage', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PeringkatFinal',
            fields=[
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='peringkat_final', serialize=False, to='main.pengguna')),
                ('total_skor', models.IntegerField(default=0)),
                ('total_waktu_detik', models.IntegerField(default=0)),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_skor', 'total_waktu_detik'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=45)),
                ('token', models.CharField(max_length=45, unique=True)),
                ('guru', models.ForeignKey(db_column='id_guru', on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
            options={
                'db_table': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id_hasil_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('skor_kuis', models.IntegerField()),
                ('waktu_kuis', models.IntegerField()),
                ('percobaan_kuis', models.IntegerField()),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kuis')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='HasilEvaluasi',
            fields=[
                ('id_hasil_evaluasi', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.IntegerField()),
                ('total_benar', models.IntegerField(default=0)),
                ('waktu_evaluasi_detik', models.IntegerField(default=0)),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaKelas',
            fields=[
                ('id_anggota', models.AutoField(primary_key=True, serialize=False)),
                ('kelas', models.ForeignKey(db_column='id_kelas', on_delete=django.db.models.deletion.CASCADE, to='main.kelas')),
                ('siswa', models.ForeignKey(db_column='id_siswa', on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
            options={
                'db_table': 'anggota_kelas',
            },
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id_pertanyaan', models.AutoField(primary_key=True, serialize=False)),
                ('teks_pertanyaan', models.TextField()),
                ('jawaban_benar', models.CharField(max_length=255)),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kuis')),
            ],
        ),
        migrations.CreateModel(
            name='RincianJawaban',
            fields=[
                ('id_rincian', models.AutoField(primary_key=True, serialize=False)),
                ('id_pertanyaan_json', models.CharField(max_length=50)),
                ('teks_pertanyaan', models.TextField(default='')),
                ('jawaban_benar', models.CharField(max_length=255)),
                ('jawaban_siswa', models.CharField(max_length=255)),
                ('is_benar', models.BooleanField(default=False)),
                ('id_hasil_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_jawaban', to='main.hasilkuis')),
            ],
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nama_item', models.CharField(max_length=45)),
                ('jenis_item', models.CharField(choices=[('teks', 'Teks'), ('kuis', 'Kuis'), ('latihan', 'Latihan')], max_length=10)),
                ('urutan', models.IntegerField()),
                ('id_kuis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kuis')),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresItem',
            fields=[
                ('id_progres_item', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('belum', 'Belum Selesai'), ('proses', 'Sedang Dikerjakan'), ('selesai', 'Selesai')], max_length=10)),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='HasilGame',
            fields=[
                ('id_hasil_game', models.AutoField(primary_key=True, serialize=False)),
                ('skor_game', models.IntegerField()),
                ('waktu_game', models.IntegerField()),
                ('percobaan_game', models.IntegerField()),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
                ('id_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stagegame')),
            ],
        ),
    ]
