# Generated by Django 5.2.8 on 2025-11-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kuis', models.CharField(max_length=45)),
                ('durasi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('kata_sandi', models.CharField(max_length=45)),
                ('peran', models.CharField(choices=[('guru', 'Guru'), ('siswa', 'Siswa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('nama_section', models.CharField(max_length=45)),
                ('urutan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StageGame',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('nama_stage', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=45)),
                ('token', models.CharField(max_length=45)),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_guru', to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id_hasil_kuis', models.AutoField(primary_key=True, serialize=False)),
                ('skor_kuis', models.IntegerField()),
                ('waktu_kuis', models.IntegerField()),
                ('percobaan_kuis', models.IntegerField()),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kuis')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='HasilEvaluasi',
            fields=[
                ('id_hasil_evaluasi', models.AutoField(primary_key=True, serialize=False)),
                ('nilai', models.IntegerField()),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='AnggotaKelas',
            fields=[
                ('id_anggota', models.AutoField(primary_key=True, serialize=False)),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='main.kelas')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_siswa', to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nama_item', models.CharField(max_length=45)),
                ('jenis_item', models.CharField(choices=[('video', 'Video'), ('teks', 'Teks'), ('kuis', 'Kuis'), ('game', 'Game')], max_length=10)),
                ('urutan', models.IntegerField()),
                ('id_kuis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kuis')),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresItem',
            fields=[
                ('id_progres_item', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('belum', 'Belum Selesai'), ('proses', 'Sedang Dikerjakan'), ('selesai', 'Selesai')], max_length=10)),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sectionitem')),
            ],
        ),
        migrations.CreateModel(
            name='HasilGame',
            fields=[
                ('id_hasil_game', models.AutoField(primary_key=True, serialize=False)),
                ('skor_game', models.IntegerField()),
                ('waktu_game', models.IntegerField()),
                ('percobaan_game', models.IntegerField()),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
                ('id_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stagegame')),
            ],
        ),
    ]
