# Generated by Django 5.2.8 on 2025-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='kata_sandi',
            field=models.CharField(max_length=255),
        ),
    ]
