# Generated by Django 5.2.8 on 2025-11-21 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_alter_pengguna_kata_sandi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeringkatFinal',
            fields=[
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='peringkat_final', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_skor', models.IntegerField(default=0)),
                ('total_waktu_detik', models.IntegerField(default=0)),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_skor', 'total_waktu_detik'],
            },
        ),
    ]
