# Generated by Django 5.2.8 on 2025-11-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_peringkatfinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id_pertanyaan', models.AutoField(primary_key=True, serialize=False)),
                ('teks_pertanyaan', models.TextField()),
                ('jawaban_benar', models.CharField(max_length=255)),
                ('id_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kuis')),
            ],
        ),
        migrations.CreateModel(
            name='RincianJawaban',
            fields=[
                ('id_rincian', models.AutoField(primary_key=True, serialize=False)),
                ('id_pertanyaan_json', models.CharField(max_length=50)),
                ('teks_pertanyaan', models.TextField(default='')),
                ('jawaban_benar', models.CharField(max_length=255)),
                ('jawaban_siswa', models.CharField(max_length=255)),
                ('is_benar', models.BooleanField(default=False)),
                ('id_hasil_kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_jawaban', to='main.hasilkuis')),
            ],
        ),
    ]
