# Generated by Django 5.2.8 on 2025-11-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_peringkatfinal_delete_hasilgame_delete_stagegame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeringkatFinal',
        ),
    ]
