# Generated by Django 5.2.8 on 2025-11-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_peringkatfinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeringkatFinal',
            fields=[
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='peringkat_final', serialize=False, to='main.pengguna')),
                ('total_skor', models.IntegerField(default=0)),
                ('total_waktu_detik', models.IntegerField(default=0)),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-total_skor', 'total_waktu_detik'],
            },
        ),
    ]
