# Generated by Django 5.2.8 on 2025-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pertanyaan_rincianjawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilevaluasi',
            name='total_benar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hasilevaluasi',
            name='waktu_evaluasi_detik',
            field=models.IntegerField(default=0),
        ),
    ]
